### ISSUE TITLE
Javascript Cookies en totes les pàgines

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#72]
Heu inclòs en cada pàgina el mateix javascript per gestionar les cookies. Proveu a externalitzar-lo a un fitxer js que importeu des de cada pàgina per evitar tenir codi repetit.

**Comment by agisbertb** [comment]
Fet.

**Comment by danieljesusgarcia** [comment]
El codi javascript per les cookies el podrieu ficar en un fitxer separat del main.js on només hi hagués el codi de cookies.

**Comment by agisbertb** [comment]
Fet, no se si la solució es del tot correcta però només he vist això per poder fer-ho, importo el fitxer cookies.js a main.js i s'autocrida.
