### ISSUE TITLE
Javascript benvinguda mailchimp encastat en html

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#76]
També seria millor externalitzar aquest codi fora del html.

           <script type="text/javascript">

                function handleFormSubmit() {
                    // Aquí puedes agregar lógica adicional antes del redireccionamiento, si es necesario

                    // Redirigir al usuario a tu archivo .html
                    // window.location.href = '/ProjecteANJO/Views/benvinguda.html';

                    // Devuelve false para prevenir el envío normal del formulario
                    return false;
                }

                (function ($) {
                    window.fnames = new Array();
                    window.ftypes = new Array();
                    fnames[0] = 'EMAIL';
                    ftypes[0] = 'email';
                    fnames[1] = 'FNAME';
                    ftypes[1] = 'text';
                    fnames[2] = 'LNAME';
                    ftypes[2] = 'text';
                    fnames[3] = 'ADDRESS';
                    ftypes[3] = 'address';
                    fnames[4] = 'PHONE';
                    ftypes[4] = 'phone';
                    fnames[5] = 'BIRTHDAY';
                    ftypes[5] = 'birthday';
                }(jQuery));
                var $mcj = jQuery.noConflict(true);
            </script>

**Comment by agisbertb** [comment]
Fet, codi posat a newsletter.js
