### ISSUE TITLE
Enllaços "Comprar pla" podrien portar al registre

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#83]
Els enllaços podrien portar al registre, com qualsevol altre CTA que no tingui una pàgina dedicada.

![Image](https://github.com/2DAM-202324-PROJECTE/ProjecteANJO/assets/4779164/f7312d8e-0802-4872-a005-31159ba30fad)

**Comment by agisbertb** [comment]
Afegit enllaç a registre.
