### ISSUE TITLE
Espai ample entre seccions

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#84]
En la pàgina de preus (i en tota la web en general) hi ha molt d'espai vertical entre cada secció. Us heu plantejat reduir-lo per fer-la més compacta? És un tema d'estil bastant subjectiu, però feu-li un pensament.

![Image](https://github.com/2DAM-202324-PROJECTE/ProjecteANJO/assets/4779164/9a1109c7-a5a2-44ed-9036-0975943eb1e6)

**Comment by agisbertb** [comment]
Reduït l'espai vertical a totes aquestes pàgines.
