### ISSUE TITLE
FAQs de pàgina principal inicialment oberta

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#85]
La primera FAQ apareix oberta. Normalment estan tancades, sembla un error.

![Image](https://github.com/2DAM-202324-PROJECTE/ProjecteANJO/assets/4779164/f2b8e469-6f2d-47b7-9e84-5acb1d40cea0)

**Comment by agisbertb** [comment]
Estava fet així aposta. L'he posat tancada com les altres.
