### ISSUE TITLE
Enllaços a pàgines externes s'obren en la mateixa pestanya

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#86]
La majoria sinó tots els enllaços que us porten a altres pàgines fora de la web (xxss, infojobs, ... ) s'obren en la mateixa pestanya. Sovint aquestes pàgines s'obren en altres pestanyes per a que l'usuari no perdi la pàgina principal del nostre producte. Penseu a canviar-ho en aquests casos.

**Comment by agisbertb** [comment]
Corregit a tots els enllaços de les xarxes socials i d'infojobs.
