### ISSUE TITLE
No trobo l'enllaç al document d'avís legal ni política de privacitat.

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#87]
Heu creat una pàgina de condicions (avís legal),  però no la trobo referenciada a la web. Tampoc es veu la política de privacitat.

**Comment by agisbertb** [comment]
Afegida pàgina avís legal i política de privacitat, modificada pàgina de cookies i condicions. Tots els footers actualitzats amb els links.
