### ISSUE TITLE
Imatge mapa mundial no es veu completa en mòbil

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#89]
En el meu mòbil veig la imatge del mapa mundial tallada. No queda malament, però cal considerar que la mida de la imatge no s'adapta al dispositiu i amb alguna altra imatge es pot perdre contingut rellevant. Es podria buscar alguna altra solució per ajustar la imatge al dispositiu.

![Image](https://github.com/2DAM-202324-PROJECTE/ProjecteANJO/assets/4779164/e2a78515-2a74-4928-bce0-ae5fe1b0c259)

**Comment by agisbertb** [comment]
Fet.
