### ISSUE TITLE
Icones en secció subscripció apareixen en vertical en mòbil

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteANJO#90]
Quan canvia la mida de la pantalla (mòbil) les icones ja no apareixen en la mateixa horitzontal sinó apilades deixant molt d'espai buit.

![Image](https://github.com/2DAM-202324-PROJECTE/ProjecteANJO/assets/4779164/08c7cef5-f12d-4a37-8a52-504135a6c7c8)

**Comment by agisbertb** [comment]
Afegides dos icones més per a facilitar la resolució.
